### ISSUE TITLE
Create an org for this gem?

### ISSUE THREAD

**Issue by nofxx** [auto-html/auto_html#155]
Before all ty @dejan for all the hard work. 
Just an idea: this gem has a lot of popularity and forks.
Move this to an organization and add some ppl to help you.

**Comment by zrisher** [comment]
:+1:

**Comment by dgilperez** [comment]
:+1:

**Comment by simonini** [comment]
:+1:

**Comment by dejan** [comment]
Done! Whoever wants to be a maintainer of this repo, please send me an email with the link to your fork. Thanks!
